services:
  db:
    image: postgres
    container_name: postgresDB
    restart: always
    environment:
      POSTGRES_DB: istudentDB
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:

